### ISSUE TITLE
Can't install with npm nor yarn

### ISSUE THREAD

**Issue by phibr0** [motif-software/obsimian#7]
I also get a 404 on npmjs.com: https://www.npmjs.com/package/obsimian

```ps
❯ yarn add -D obsimian
yarn add v1.22.10
warning ..\..\..\..\..\package.json: No license field
[1/4] Resolving packages...
error Received malformed response from registry for "obsimian". The registry may be down.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**Comment by orlade** [comment]
Yeah, duh, my bad. I have no experience actually publishing NPM packages, so I was trying and messing up and unpublishing, then I couldn't republish for 24 hours, then it didn't stick etc. It all feels very manual and difficult to automate reliably.

Anyway, thanks for the issue reminding me! Just published v0.4.0, now available at https://www.npmjs.com/package/obsimian. No changes, probably no changelog, etc. I'll try to get it in better shape so I can publish things more effectively.
